server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
    
spring:
  security:
    user:
      name: test
      password: 1234
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 949211390946-0pmcstq5k9emjqa0s9gp08385hglkrua.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#            - email
#            - profile
#          naver:
#            client-id: JyPem6YFgFNmmekwuWQY
#            client-secret: rUdsTctw1c
#            scope:
#            - email
#            - name
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8000/login/oauth2/code/naver
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web1.cgmmemndynvq.ap-northeast-2.rds.amazonaws.com:3306/project?useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: 1q2w3e4r
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file:
  path: ./src/main/resources/static/upload/